### ISSUE TITLE
The "Get Started" guide does not work.

### ISSUE THREAD

**Issue by urasawa11** [rarible/ethereum-indexer-public#540]
I saw [Get Started](https://github.com/rarible/ethereum-indexer#get-started) and followed it, but it doesn't work.
[docker/.env](https://github.com/rarible/ethereum-indexer/blob/master/docker/.env), [docker/docker-compose.yaml](https://github.com/rarible/ethereum-indexer/blob/master/docker/docker-compose.yaml) file update is required.

please update or guide to build in local environment

**Comment by sanufriev** [comment]
Hi, I made some fixes and now it works for me. Please try on "master" and if something wrong, share error logs

**Comment by urasawa11** [comment]
# I had some issues
[WARN] in nft-listener, erc20-listener
```
2023-01-17 05:08:40.751  WARN 1 --- [ory.listener-23] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=local.0052d9826022.3a95fa64-9f10-434e-8cd0-43ccf4a92fc3.ethereum.log-event-consumer.nft.local.protocol.ethereum.nft.token.history.listener-10, groupId=local.protocol.ethereum.nft.token.history.listener] Error while fetching metadata with correlation id 868 : {protocol.local.ethereum.blockchain-scanner.nft.log.token-history=UNKNOWN_TOPIC_OR_PARTITION}
```

[ERROR] in gateway
```
GET "/v0.1/nft/items/all"

java.net.UnknownHostException: Failed to resolve 'ethereum-nft-api' after 2 queries 
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/v0.1/nft/items/all" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
                at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
                at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
                at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:629)
                at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:66)
                at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:462)
                at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
                at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
                at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
                at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
                at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
                at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
                at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
                at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:232)
                at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:224)
                at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1314)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:648)
                at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:683)
                at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:55)
                at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:522)
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:750)
```

# This my parameter set for syncing ethereum
### in .env file
```
BLOCKCHAIN=ethereum
CHAIN_ID=1
```
### in docker-compose.yaml
```
  protocol-ethereum:
    image: rarible/openethereum
    command: >
      --base-path /home/openethereum/.local/share/openethereum/
      --jsonrpc-interface all
      --jsonrpc-cors all
      --unsafe-expose
    user: root:root
    volumes:
      - protocol-ethereum:/home/openethereum/.local/share/openethereum/
    ports:
      - "8545:8545"
    depends_on:
      - "protocol-redis"
```

I think i need more setting info for working this code.
and I need more information that method for syncing goerli
